### ISSUE TITLE
Since no one comments here, wanted to share my experience 

### ISSUE THREAD

**Issue by dinpwr** [milutinke/Discord-Server-Channel-Attachment-Downloader-BOT#1]
Hi!
I tried 2-3 bots/scripts to download images from my and friends channel to find our old photos(easier to sort downloaded versions etc.) and none of them worked for me (for several reasons, probably too old and API changed or something).

This one didn't work until i changed package.json. First string "name" gives error since you used spaces and capitalized letters (i am kinda new to programming, so maybe it changed from the time you made the code). 
Some packages didn't load too, but it worked anyway.
Thanks! Just wanted to leave something, for people who are searching for bot like this.

**Comment by milutinke** [comment]
Thanks for the feedback.
It seems that NodeJS does not allow spaces in the name anymore, I will fix that.
I will also remove that 15 seconds delay before the download, I will initiate download when the last line of the file has been read.

**Comment by milutinke** [comment]
Fixed.
