### ISSUE TITLE
[Inquiries]

### ISSUE THREAD

**Issue by Kirekus** [milutinke/Discord-Server-Channel-Attachment-Downloader-BOT#2]
Is there a way to clean the files that were previously "npm run fetch"? I am unable to delete the history as such the files  downloaded keep increases incrementally. In this scenario, I "npm run fetch" 20 files, then when i rerun the program and call upon the command once more it increase 20 (before) + # [current number for this command] and so on.

**Comment by milutinke** [comment]
Just delete attachments.txt before you run the command.
I will soon make a v2. 
I will make that everything runs with a single command and that you can select the channel from the menu, and that you can choose which types of files you want to download.
If you have any suggestions, leave them here.

**Comment by Kirekus** [comment]
Oh that would be very neat! Also, thank you! Deleting attachments.txt fixed the issue!
